--[[
	Smart Scatter — Engine (ModuleScript, child of the plugin Script)
	Upright placement: a model's "up" is how it stands in the world, never its pivot rotation.
	Area mask → scan (surface classes + distance fields) → rule-based procedural placement.
	GENERATED by tools/bundle_engine.py from src/engine/NN_*.lua (one shared scope, concatenated in order):
	01 core · 02 surfaces · 03 assets & layers · 04 areas, saving & mask editing · 05 scan · 06 splines · 07 roads ·
	08 planning · 09 placement · 10 lines & splines · 11 generate. Edit the parts, not this file.
]]

local CollectionService = game:GetService("CollectionService")
local HttpService = game:GetService("HttpService")

local E = {}
E.TAG = "SmartScatter"
E.OUT = "SmartScatter"
E.ROADS = "SmartScatter Roads" -- road surfaces, one folder per area (kept outside E.OUT so raycasts hit them)
E.MASK_CELL = 4 -- area mask resolution in studs (older 8-stud areas are upgraded on load)
