"""Bundle src/*.lua into Main.lua (+ Main_2.lua, Main_3.lua… when needed): the ModuleScripts the loader runs.

Each src module is `return function(App) ... end`; the bundle runs them in ORDER against one shared App table.
Each module is its own function, so each gets its own 200-local budget.

Studio refuses a script Source of 200,000 characters or more when it's set from code (the loader and the live mirror
both do that), so modules are packed into parts well under the limit. Main.lua is the entry: it holds the first
modules and the runner, and requires its siblings Main_2, Main_3… for the rest."""
import pathlib

here = pathlib.Path(__file__).resolve().parent.parent
ORDER = ["Base", "Kit", "Overlay", "Core", "Header", "AreaPage", "ObjectsPage", "Shell", "Paint", "Spline", "Tour", "Main"]
LIMIT = 180_000  # bytes per part, leaving room under Studio's 200k


def block(name):
    src = (here / "src" / (name + ".lua")).read_text(encoding="utf-8").replace("\r\n", "\n").rstrip("\n")
    return "\n".join(["", "-- #module %s" % name, "MODULES[%d] = (function()" % (ORDER.index(name) + 1), src, "end)()"])


HEAD = [
    "--[[",
    "\tSmart Scatter — Main. GENERATED by tools/bundle.py from src/*.lua: edit the modules, not this file.",
    "\tModules run in order against one shared App table (state and cross-module functions).",
    "]]",
    "",
    "local MODULES = {}",
]
RUNNER = [
    "",
    "-- the rest of the modules live in sibling parts (Main_2, Main_3…); an older loader that only copies Main",
    "-- finds them in the live mirror instead",
    "local function part(name)",
    "\tlocal p = script.Parent and script.Parent:FindFirstChild(name)",
    "\tif not p then",
    '\t\tlocal m = game:GetService("ServerStorage"):FindFirstChild("SmartScatterSource")',
    "\t\tp = m and m:FindFirstChild(name)",
    "\tend",
    "\treturn p",
    "end",
    "for k = 2, 16 do",
    '\tlocal p = part("Main_" .. k)',
    "\tif not p then",
    "\t\tbreak",
    "\tend",
    "\tfor i, f in require(p) do",
    "\t\tMODULES[i] = f",
    "\tend",
    "end",
    "",
    "return function(ctx)",
    "\tlocal App = { ctx = ctx }",
    "\tlocal cleanup",
    "\tfor i = 1, #MODULES do",
    "\t\tlocal r = MODULES[i](App)",
    "\t\tif r ~= nil then",
    "\t\t\tcleanup = r",
    "\t\tend",
    "\tend",
    "\treturn cleanup",
    "end",
    "",
]
PART_HEAD = [
    "--[[",
    "\tSmart Scatter — Main, part %d. GENERATED by tools/bundle.py from src/*.lua: edit the modules, not this file.",
    "\tRequired by Main; returns its modules by their place in the run order.",
    "]]",
    "",
    "local MODULES = {}",
]

# pack modules in order: the entry first (it also carries the runner), then as many parts as needed
blocks = [block(n) for n in ORDER]
size = lambda lines: len("\n".join(lines).encode())
chunks, cur = [], []
budget = LIMIT - size(HEAD) - size(RUNNER)
for b in blocks:
    if cur and size(cur + [b]) > budget:
        chunks.append(cur)
        cur, budget = [], LIMIT - size(PART_HEAD) - 40
    cur.append(b)
chunks.append(cur)

for old in [p for p in here.glob("Main_[0-9]*.lua") if p.stem[5:].isdigit()]:
    old.unlink()
entry = "\n".join(HEAD + chunks[0] + RUNNER)
(here / "Main.lua").write_bytes((entry).encode("utf-8"))
sizes = [len(entry.encode())]
for k, ch in enumerate(chunks[1:], start=2):
    text = "\n".join([l % k if "%d" in l else l for l in PART_HEAD] + ch + ["", "return MODULES", ""])
    (here / ("Main_%d.lua" % k)).write_bytes((text).encode("utf-8"))
    sizes.append(len(text.encode()))
assert all(s < 195_000 for s in sizes), sizes
print("Main.lua", " + ".join(str(s) for s in sizes), "bytes in", len(sizes), "part(s) from", len(ORDER), "modules")
